osx_image: xcode7.2
language: objective-c
xcode_project: MMDB.xcodeproj
xcode_scheme: MMDB-iOS
xcode_sdk: iphonesimulator
env:
  global:
    - FRAMEWORK_NAME=MMDB
before_install:
  - brew update
  - brew install carthage
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: repo/repo
    tags: true
